-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local term = os.getenv("HYPR_DOTS_TERM") or "kitty"
local files = os.getenv("HYPR_DOTS_FILES") or "thunar"

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Default Keybinds

-- visit https://wiki.hyprland.org/Configuring/Binds/ for more info

-- /* ---- ✴️ Variables ✴️ ---- */  #

local mainMod = "SUPER"

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

local UserConfigs = os.getenv("HOME") .. "/.config/hypr/UserConfigs"

local UserScripts = os.getenv("HOME") .. "/.config/hypr/UserScripts"

-- settings for User defaults apps - set your default terminal and file manager on this file


--### STANDAR ####

-- Common shortcuts

--bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window # Super Key to Launch rofi menu

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("pkill rofi || true && rofi -show drun -modi drun"))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("xdg-open \"https://\""))

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/OverviewToggle.sh"))

-- toggles quickshell or ags overview (tries QS first, falls back to AGS)

--bindd = $mainMod, A, ags overview, exec, pkill rofi || true && ags -t 'overview' # desktop overview (if installed)

--bindd = $mainMod, A, Quickshell overview, global, quickshell:overviewToggle # desktop overview (if installed)

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd(term))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(files))

-- FEATURES / EXTRAS

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ThemeChanger.sh"))

--Global theme switcher

hl.bind(mainMod .. " + " .. "H", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KeyHints.sh"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "R", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Refresh.sh"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "E", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/RofiEmoji.sh"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/RofiSearch.sh"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "S", hl.dsp.exec_cmd("rofi -show window"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "O", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ChangeBlur.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/GameMode.sh"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "L", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ChangeLayout.sh"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "V", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ClipManager.sh"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "R", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/RofiThemeSelector.sh"))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("pkill rofi || true && " .. os.getenv("HOME") .. "/.config/hypr/scripts/RofiThemeSelector-modified.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "SPACE", hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Dropterminal.sh " .. term))

-- Desktop zooming or magnifier

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "mouse_down", hl.dsp.exec_cmd([[bash -c 'factor=$(hyprctl -j getoption cursor.zoom_factor | jq -r .float); awk -v f="$factor" "BEGIN { if (f < 1) f = 1; print f * 2 }" | xargs -I{} hyprctl eval "hl.config({ cursor = { zoom_factor = {} } })"']]))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "mouse_up", hl.dsp.exec_cmd([[bash -c 'factor=$(hyprctl -j getoption cursor.zoom_factor | jq -r .float); awk -v f="$factor" "BEGIN { if (f < 1) f = 1; print f / 2 }" | xargs -I{} hyprctl eval "hl.config({ cursor = { zoom_factor = {} } })"']]))

-- Waybar / Bar related

hl.bind(mainMod .. " + " .. "CTRL + ALT" .. " + " .. "B", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "B", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/WaybarStyles.sh"))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "B", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/WaybarLayout.sh"))

-- Night light toggle (Hyprsunset)

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Hyprsunset.sh toggle"))

-- FEATURES / EXTRAS (UserScripts)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/UserScripts/RofiBeats.sh"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/UserScripts/WallpaperSelect.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/UserScripts/WallpaperEffects.sh"))

hl.bind("CTRL + ALT + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/UserScripts/WallpaperRandom.sh"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "O", hl.dsp.window.set_prop({ prop = "opaque", value = "toggle" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KeyBinds.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Animations.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "O", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/UserScripts/ZshChangeTheme.sh"))

hl.bind("ALT_L + SHIFT_L", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KeyboardLayout.sh switch"), { locked = true, non_consuming = true })

hl.bind("SHIFT_L + ALT_L", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Tak0-Per-Window-Switch.sh"), { locked = true, non_consuming = true })

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "C", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/UserScripts/RofiCalc.sh"))

-- Move current workspaces to monitors (left right up or down)

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F9", hl.dsp.workspace.move({ monitor = "l" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F10", hl.dsp.workspace.move({ monitor = "r" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F11", hl.dsp.workspace.move({ monitor = "u" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F12", hl.dsp.workspace.move({ monitor = "d" }))

--### SYSTEM ####

hl.bind("CTRL + ALT + Delete", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KillActiveProcess.sh"))

hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/LockScreen.sh"))

hl.bind("CTRL + ALT + P", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Wlogout.sh"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t -sw"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Kool_Quick_Settings.sh"))

-- Master Layout

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "D", hl.dsp.layout("removemaster"))

hl.bind(mainMod .. " + " .. "I", hl.dsp.layout("addmaster"))

-- NOTE: J/K bindings are set dynamically by scripts/KeybindsLayoutInit.sh and scripts/ChangeLayout.sh

-- (we intentionally do not bind them statically here to avoid conflicts across layouts)

-- bindd = $mainMod, J, cycle next, layoutmsg, cyclenext

-- bindd = $mainMod, K, cycle previous, layoutmsg, cycleprev

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Return", hl.dsp.layout("swapwithmaster"))

-- Dwindle Layout

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "I", hl.dsp.layout("togglesplit"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- Works on either layout (Master or Dwindle)

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("hyprctl dispatch splitratio 0.3"))

-- layout aware keybinds


-- Cycle windows; if floating bring to top

hl.bind("ALT + tab", hl.dsp.window.cycle_next())

hl.bind("ALT + tab", hl.dsp.window.bring_to_top())

-- Special Keys / Hot Keys

hl.bind("XF86audioraisevolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --inc"), { locked = true })

hl.bind("XF86audiolowervolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --dec"), { locked = true })

hl.bind("ALT + XF86audioraisevolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --inc-precise"), { locked = true })

hl.bind("ALT + XF86audiolowervolume", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --dec-precise"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --toggle-mic"), { locked = true })

hl.bind("XF86audiomute", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Volume.sh --toggle"), { locked = true })

hl.bind("XF86Sleep", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })

hl.bind("XF86Rfkill", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/AirplaneMode.sh"), { locked = true })

-- media controls using keyboards


hl.bind("XF86AudioPause", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --pause"), { locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --nxt"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --prv"), { locked = true })

hl.bind("XF86audiostop", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/MediaCtrl.sh --stop"), { locked = true })

-- Screenshot keybindings NOTE: You may need to press Fn key as well

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --now"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --area"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --in5"))

hl.bind(mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --in10"))

hl.bind("ALT + Print", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --active"))

-- screenshot with swappy (another screenshot tool)

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ScreenShot.sh --swappy"))

-- Resize windows

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- Move windows

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.window.move({ direction = "down" }))

-- Swap windows

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "left", hl.dsp.window.swap({ direction = "left" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "right", hl.dsp.window.swap({ direction = "right" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "up", hl.dsp.window.swap({ direction = "up" }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "down", hl.dsp.window.swap({ direction = "down" }))

-- group

hl.bind(mainMod .. " + " .. "G", hl.dsp.group.toggle())

-- Navigate within a group

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.group.next())

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "tab", hl.dsp.group.next({ forward = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.group.next({ forward = false }))

-- Move window into/out of group

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.window.move({ into_group = "left" }))

-- Move active window left into a group A

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.window.move({ into_group = "right" }))

-- Move active window right into a group

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.window.move({ out_of_group = true }))

-- Move active window out of group

-- Try to dynamically move in grouped window and when ungrouped

--  Not working for me DW 11/26/25  PR: https://github.com/JaKooLit/Hyprland-Dots/pull/872

--bindd = $mainMod, right, focus right, exec, bash -c 'if hyprctl activewindow -j | jq -e "((.grouped | type) == \"boolean\") or (.address == (.grouped[-1] // empty))" >/dev/null 2>&1; then hyprctl dispatch movefocus r; else hyprctl dispatch changegroupactive f; fi'

--bindd = $mainMod, left, focus left, exec, bash -c 'if hyprctl activewindow -j | jq -e "((.grouped | type) == \"boolean\") or (.address == (.grouped[0] // empty))" >/dev/null 2>&1; then hyprctl dispatch movefocus l; else hyprctl dispatch changegroupactive b; fi'

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Workspaces related

hl.bind(mainMod .. " + " .. "tab", hl.dsp.focus({ workspace = "m+1" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "tab", hl.dsp.focus({ workspace = "m-1" }))

-- Special workspace

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "U", hl.dsp.window.move({ workspace = "special" }))

hl.bind(mainMod .. " + " .. "U", hl.dsp.workspace.toggle_special())

-- The following mappings use the key codes to better support various keyboard layouts

-- 1 is code:10, 2 is code 11, etc

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))

-- NOTE: code:10 = key 1

hl.bind(mainMod .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))

-- NOTE: code:11 = key 2

hl.bind(mainMod .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))

-- NOTE: code:12 = key 3

hl.bind(mainMod .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))

-- NOTE: code:13 = key 4

hl.bind(mainMod .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))

-- NOTE: code:14 = key 5

hl.bind(mainMod .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))

-- NOTE: code:15 = key 6

hl.bind(mainMod .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))

-- NOTE: code:16 = key 7

hl.bind(mainMod .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))

-- NOTE: code:17 = key 8

hl.bind(mainMod .. " + " .. "code:18", hl.dsp.focus({ workspace = 9 }))

-- NOTE: code:18 = key 9

hl.bind(mainMod .. " + " .. "code:19", hl.dsp.focus({ workspace = 10 }))

-- NOTE: code:19 = key 0

-- Move active window and follow to workspace mainMod + SHIFT [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))

-- NOTE: code:10 = key 1

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))

-- NOTE: code:11 = key 2

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))

-- NOTE: code:12 = key 3

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))

-- NOTE: code:13 = key 4

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))

-- NOTE: code:14 = key 5

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))

-- NOTE: code:15 = key 6

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))

-- NOTE: code:16 = key 7

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))

-- NOTE: code:17 = key 8

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 }))

-- NOTE: code:18 = key 9

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 }))

-- NOTE: code:19 = key 0

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "bracketleft", hl.dsp.window.move({ workspace = "-1" }))

-- brackets [

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "bracketright", hl.dsp.window.move({ workspace = "+1" }))

-- brackets ]

-- Move active window to a workspace silently mainMod + CTRL [0-9]

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 , follow = false}))

-- NOTE: code:10 = key 1

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 , follow = false}))

-- NOTE: code:11 = key 2

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 , follow = false}))

-- NOTE: code:12 = key 3

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 , follow = false}))

-- NOTE: code:13 = key 4

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 , follow = false}))

-- NOTE: code:14 = key 5

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 , follow = false}))

-- NOTE: code:15 = key 6

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 , follow = false}))

-- NOTE: code:16 = key 7

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 , follow = false}))

-- NOTE: code:17 = key 8

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:18", hl.dsp.window.move({ workspace = 9 , follow = false}))

-- NOTE: code:18 = key 9

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:19", hl.dsp.window.move({ workspace = 10 , follow = false}))

-- NOTE: code:19 = key 0

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "bracketleft", hl.dsp.window.move({ workspace = "-1" , follow = false}))

-- brackets [

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "bracketright", hl.dsp.window.move({ workspace = "+1" , follow = false}))

-- brackets ]

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + " .. "period", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "comma", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

-- NOTE: mouse:272 = left click

hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- NOTE: mouse:272 = right click

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/ChangeLayout.sh init")
end)
