-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Commands and Apps to be executed at launch (vendor defaults)

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

local UserScripts = os.getenv("HOME") .. "/.config/hypr/UserScripts"

local lock = os.getenv("HOME") .. "/.config/hypr/scripts/LockScreen.sh"

local SwwwRandom = os.getenv("HOME") .. "/.config/hypr/UserScripts/WallpaperAutoChange.sh"

local livewallpaper = ""

local wallDIR = os.getenv("HOME") .. "/Pictures/wallpapers"

-- change path manually here if needed

--## wallpaper stuff ###


--exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

-- wallpaper random

--exec-once = $SwwwRandom $wallDIR # random wallpaper switcher every 30 minutes

--## Startup ###







-- For ubuntu


--exec-once = ags

--exec-once = blueman-applet

--exec-once = rog-control-center



-- Quickshell Overview



-- Clipboard manager



-- Rainbow borders (disabled by default; use quick settings menu)

--exec-once = $UserScripts/RainbowBorders.sh

-- Here are list of features available but disabled by default

-- Persistent wallpaper

-- exec-once = $scriptsDir/WallpaperDaemon.sh && swww img $wallDIR/mecha-nostalgia.png

-- Gnome polkit for NixOS

--exec-once = $scriptsDir/Polkit-NixOS.sh

-- xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)

--exec-once = $scriptsDir/PortalHyprland.sh



-- Quickshell Overview


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/WallpaperDaemon.sh")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Dropterminal.sh kitty &")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Polkit.sh")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("nm-tray")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("qs -c overview")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/Hyprsunset.sh init")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("qs -c overview")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/KeybindsLayoutInit.sh")
end)
