-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Default settings

-- This is where you put your own settings as this will not be touched during update 

-- if the upgrade.sh is used.

-- refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/

-- NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

hl.config({
    dwindle = {
        -- Removed in Hyprland 0.55; use the pseudo dispatcher/keybind instead.
        -- pseudotile = true
        preserve_split = true,
        --smart_split = true
        special_scale_factor = 0.8,
    },
})

hl.config({
    master = {
        new_status = "master",
        new_on_top = 1,
        mfact = 0.5,
    },
})

hl.config({
    general = {
        resize_on_border = true,
        layout = "dwindle",
    },
})

hl.config({
    input = {
        kb_layout = "br",
        repeat_rate = 50,
        repeat_delay = 300,
        sensitivity = 0,
        --mouse sensitivity
        --accel_profile =     # flat or adaptive or blank or EMPTY means libinput’s default mode
        numlock_by_default = true,
        left_handed = false,
        follow_mouse = 1,
        float_switch_override_focus = false,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            clickfinger_behavior = false,
            middle_button_emulation = false,
            tap_to_click = true,
            drag_lock = false,
        },
        -- below for devices with touchdevice ie. touchscreen
        touchdevice = {
            enabled = true,
        },
        -- below is for table see link above for proper variables
        tablet = {
            transform = 0,
            left_handed = 0,
        },
    },
})

hl.config({
    gestures = {
        workspace_swipe_distance = 500,
        workspace_swipe_invert = true,
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_cancel_ratio = 0.5,
        workspace_swipe_create_new = true,
        workspace_swipe_forever = true,
        --workspace_swipe_use_r = true #uncomment if wanted a forever create a new workspace with swipe right
    },
})
hl.gesture({
    ["fingers"] = 3,
    ["direction"] = "horizontal",
    ["action"] = "workspace",
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        -- Removed in Hyprland 0.55.
        -- vfr = true
        vrr = 2,
        mouse_move_enables_dpms = true,
        enable_swallow = false,
        swallow_regex = "^(kitty)$",
        focus_on_activate = false,
        initial_workspace_tracking = 0,
        middle_click_paste = false,
        enable_anr_dialog = true,
        -- Application not Responding (ANR)
        anr_missed_pings = 15,
        -- ANR Threshold default 1 is too low
        allow_session_lock_restore = true,
        -- Prevent lockscreen crash when resume from suspend
        -- This only works with HL v0.53+
        on_focus_under_fullscreen = 1,
        -- 0 - Default, no change
        -- 1 - New focused window takes over fullscreen (Windows-like Alt-Tab)
        -- 2 - New focused window stays behind the fullscreen one
    },
})

--opengl {

--  nvidia_anti_flicker = true

--}

hl.config({
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },
})

--Could help when scaling and not pixelating

hl.config({
    xwayland = {
        enabled = true,
        force_zero_scaling = true,
    },
})

hl.config({
    render = {
        direct_scanout = 0,
    },
})

hl.config({
    cursor = {
        sync_gsettings_theme = true,
        no_hardware_cursors = 1,
        -- change to 1 if want to disable
        enable_hyprcursor = true,
        warp_on_change_workspace = 2,
        no_warps = true,
    },
})
