-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Vendor defaults for window rules and layerrules

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- NOTES: This is only for Hyprland >= 0.53

--  Some samples on hwo to start apps on specific workspaces 

-- windowrule = match:tag email*, workspace 1

-- windowrule = match:tag browser*, workspace 2

-- windowrule = match:tag projects*, workspace 3

-- windowrule = match:tag screenshare*, workspace 4 silent

-- windowrule = match:tag gamestore*, workspace 5

-- windowrule = match:class ^(virt-manager)$, workspace 6 silent

-- windowrule = match:class ^(.virt-manager-wrapped)$, workspace 6 silent

-- windowrule = match:tag im*, workspace 7

-- windowrule = match:class obsidian, workspace 8

-- windowrule = match:tag games*, workspace 8

-- windowrule = match:tag multimedia*, workspace 9 silent

-- TAGS - add apps under appropriate tag to use the same settings

-- browser tags

hl.window_rule({
    name  = "tag__browser_24",
    match = {
        class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name  = "tag__browser_25",
    match = {
        class = "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name  = "tag__browser_26",
    match = {
        class = "^(chrome-.+-Default)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name  = "tag__browser_27",
    match = {
        class = "^([Cc]hromium)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name  = "tag__browser_28",
    match = {
        class = "^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$",
    },
    tag = "+browser",
})

hl.window_rule({
    name  = "tag__browser_29",
    match = {
        class = "^(Brave-browser(-beta|-dev|-unstable)?)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name  = "tag__browser_30",
    match = {
        class = "^([Tt]horium-browser|[Cc]achy-browser)$",
    },
    tag = "+browser",
})

hl.window_rule({
    name  = "tag__browser_31",
    match = {
        class = "^(zen-alpha|zen)$",
    },
    tag = "+browser",
})

-- notif tags

hl.window_rule({
    name  = "tag__notif_34",
    match = {
        class = "^(swaync-control-center|swaync-notification-window|swaync-client|class)$",
    },
    tag = "+notif",
})

-- KooL settings tag

hl.window_rule({
    name  = "tag__kool_cheat_37",
    match = {
        title = "^(KooL Quick Cheat Sheet)$",
    },
    tag = "+KooL_Cheat",
})

hl.window_rule({
    name  = "tag__kool_settings_38",
    match = {
        title = "^(KooL Hyprland Settings)$",
    },
    tag = "+KooL_Settings",
})

hl.window_rule({
    name  = "tag__kool-settings_39",
    match = {
        class = "^(nwg-displays|nwg-look)$",
    },
    tag = "+KooL-Settings",
})

-- terminal tags

hl.window_rule({
    name  = "tag__terminal_42",
    match = {
        class = "^(Alacritty|kitty|kitty-dropterm)$",
    },
    tag = "+terminal",
})

-- email tags

hl.window_rule({
    name  = "tag__email_45",
    match = {
        class = "^([Tt]hunderbird|org.mozilla.Thunderbird)$",
    },
    tag = "+email",
})

hl.window_rule({
    name  = "tag__email_46",
    match = {
        class = "^(eu.betterbird.Betterbird)$",
    },
    tag = "+email",
})

hl.window_rule({
    name  = "tag__email_47",
    match = {
        class = "^(org.gnome.Evolution)$",
    },
    tag = "+email",
})

-- project tags

hl.window_rule({
    name  = "tag__projects_50",
    match = {
        class = "^(codium|codium-url-handler|VSCodium)$",
    },
    tag = "+projects",
})

hl.window_rule({
    name  = "tag__projects_51",
    match = {
        class = "^(VSCode|code|code-url-handler)$",
    },
    tag = "+projects",
})

hl.window_rule({
    name  = "tag__projects_52",
    match = {
        class = "^(jetbrains-.+)$",
    },
    tag = "+projects",
})

hl.window_rule({
    name  = "tag__projects_53",
    match = {
        class = "^(dev.zed.Zed|antigravity)$",
    },
    tag = "+projects",
})

-- screenshare tags

hl.window_rule({
    name  = "tag__screenshare_56",
    match = {
        class = "^(com.obsproject.Studio)$",
    },
    tag = "+screenshare",
})

-- IM tags

hl.window_rule({
    name  = "tag__im_59",
    match = {
        class = "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$",
    },
    tag = "+im",
})

hl.window_rule({
    name  = "tag__im_60",
    match = {
        class = "^([Ff]erdium)$",
    },
    tag = "+im",
})

hl.window_rule({
    name  = "tag__im_61",
    match = {
        class = "^([Ww]hatsapp-for-linux)$",
    },
    tag = "+im",
})

hl.window_rule({
    name  = "tag__im_62",
    match = {
        class = "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$",
    },
    tag = "+im",
})

hl.window_rule({
    name  = "tag__im_63",
    match = {
        class = "^(teams-for-linux)$",
    },
    tag = "+im",
})

hl.window_rule({
    name  = "tag__im_64",
    match = {
        class = "^(im.riot.Riot|Element)$",
    },
    tag = "+im",
})

-- game tags

hl.window_rule({
    name  = "tag__games_67",
    match = {
        class = "^(gamescope)$",
    },
    tag = "+games",
})

hl.window_rule({
    name  = "tag__games_68",
    match = {
        class = "^(steam_app_\\\\d+)$",
    },
    tag = "+games",
})

-- gamestore tags

hl.window_rule({
    name  = "tag__gamestore_71",
    match = {
        class = "^([Ss]team)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    name  = "tag__gamestore_72",
    match = {
        title = "^([Ll]utris)$",
    },
    tag = "+gamestore",
})

hl.window_rule({
    name  = "tag__gamestore_73",
    match = {
        class = "^(com.heroicgameslauncher.hgl)$",
    },
    tag = "+gamestore",
})

-- file-manager tags

hl.window_rule({
    name  = "tag__file-manager_76",
    match = {
        class = "^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$",
    },
    tag = "+file-manager",
})

hl.window_rule({
    name  = "tag__file-manager_77",
    match = {
        class = "^(app.drey.Warp)$",
    },
    tag = "+file-manager",
})

-- wallpaper tags

hl.window_rule({
    name  = "tag__wallpaper_80",
    match = {
        class = "^([Ww]aytrogen)$",
    },
    tag = "+wallpaper",
})

-- multimedia tags

hl.window_rule({
    name  = "tag__multimedia_83",
    match = {
        class = "^([Aa]udacious)$",
    },
    tag = "+multimedia",
})

-- multimedia-video tags

hl.window_rule({
    name  = "tag__multimedia_vide_86",
    match = {
        class = "^([Mm]pv|vlc)$",
    },
    tag = "+multimedia_video",
})

-- settings tags

hl.window_rule({
    name  = "tag__settings_89",
    match = {
        title = "^(ROG Control)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_90",
    match = {
        class = "^(wihotspot(-gui)?)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_91",
    match = {
        class = "^([Bb]aobab|org.gnome.[Bb]aobab)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_92",
    match = {
        class = "^(gnome-disks|wihotspot(-gui)?)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_93",
    match = {
        title = "(Kvantum Manager)",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_94",
    match = {
        class = "^(file-roller|org.gnome.FileRoller)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_95",
    match = {
        class = "^(nm-applet|nm-connection-editor|blueman-manager)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_96",
    match = {
        class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_97",
    match = {
        class = "^(qt5ct|qt6ct)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_98",
    match = {
        class = "(xdg-desktop-portal-gtk)",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_99",
    match = {
        class = "^(org.kde.polkit-kde-authentication-agent-1)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_100",
    match = {
        class = "^([Rr]ofi)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_101",
    match = {
        class = "^(btrfs-assistant)$",
    },
    tag = "+settings",
})

hl.window_rule({
    name  = "tag__settings_102",
    match = {
        class = "^(timeshift-gtk)$",
    },
    tag = "+settings",
})

-- viewer tags

hl.window_rule({
    name  = "tag__viewer_105",
    match = {
        class = "^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    name  = "tag__viewer_106",
    match = {
        class = "^(evince)$",
    },
    tag = "+viewer",
})

hl.window_rule({
    name  = "tag__viewer_107",
    match = {
        class = "^(eog|org.gnome.Loupe)$",
    },
    tag = "+viewer",
})

-- Some special override rules

hl.window_rule({
    name  = "no_blur_on_110",
    match = {
        tag = "multimedia_video",
    },
    no_blur = true,
})

hl.window_rule({
    name  = "opacity_1_0_111",
    match = {
        tag = "multimedia_video",
    },
    opacity = "1.0",
})

hl.window_rule({
    name  = "no_blur_on_112",
    match = {
        tag = "multimedia",
    },
    no_blur = true,
})

hl.window_rule({
    name  = "opacity_1_0_113",
    match = {
        tag = "multimedia",
    },
    opacity = "1.0",
})

-- POSITION

hl.window_rule({
    name  = "center_on_116",
    match = {
        tag = "KooL_Cheat",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on_117",
    match = {
        tag = "KooL-Settings",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on_118",
    match = {
        title = "^(ROG Control)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on_119",
    match = {
        title = "^(Keybindings)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on_120",
    match = {
        class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$",
    },
    center = true,
})

hl.window_rule({
    name  = "center_on_121",
    match = {
        class = "^([Ff]erdium)$",
    },
    center = true,
})

-- windowrule to avoid idle for fullscreen apps

hl.window_rule({
    name  = "idle_inhibit_fullscr_124",
    match = {
        fullscreen = true,
    },
    idle_inhibit = "fullscreen",
})

hl.window_rule({
    name  = "idle_inhibit_fullscr_125",
    match = {
        fullscreen = 1,
    },
    idle_inhibit = "fullscreen",
})

-- FLOAT

hl.window_rule({
    name  = "float_on_130",
    match = {
        tag = "KooL_Cheat",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_131",
    match = {
        tag = "wallpaper",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "float_on_132",
    match = {
        tag = "settings",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "float_on_133",
    match = {
        tag = "viewer",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "float_on_134",
    match = {
        tag = "KooL-Settings",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "float_on_135",
    match = {
        class = "([Zz]oom|onedriver|onedriver-launcher)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_136",
    match = {
        class = "(org.gnome.Calculator|qalculate-gtk)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_137",
    match = {
        class = "^(mpv|com.github.rafostar.Clapper)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_138",
    match = {
        class = "^([Qq]alculate-gtk)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_139",
    match = {
        class = "^([Ff]erdium)$",
    },
    float = true,
})

-- popups and dialogue 

hl.window_rule({
    name  = "float_on_142",
    match = {
        title = "^(Authentication Required)$",
    },
    float = true,
    center = true,
})

hl.window_rule({
    name  = "float_on_143",
    match = {
        class = "(codium|codium-url-handler|VSCodium) match:title negative:(.*codium.*|.*VSCodium.*)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_144",
    match = {
        class = "^(com.heroicgameslauncher.hgl)$ match:title negative:(Heroic Games Launcher)",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_145",
    match = {
        class = "^([Ss]team)$ match:title negative:^([Ss]team)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on_146",
    match = {
        title = "^(Add Folder to Workspace)$",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
    center = true,
})

hl.window_rule({
    name  = "float_on_147",
    match = {
        title = "^(Save As)$",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
    center = true,
})

hl.window_rule({
    name  = "float_on_148",
    match = {
        initial_title = "(Open Files)",
    },
    float = true,
    size = { "(monitor_w*0.7)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "float_on_149",
    match = {
        title = "^(SDDM Background)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.16)", "(monitor_h*0.12)" },
})

hl.window_rule({
    name  = "float_on_150",
    match = {
        class = "^(yad)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.2)", "(monitor_h*0.2)" },
})

hl.window_rule({
    name  = "float_on_151",
    match = {
        class = "^(hyprland-donate-screen)$",
    },
    float = true,
    center = true,
})

-- OPACITY

hl.window_rule({
    name  = "opacity_1_1_154",
    match = {
        tag = "browser",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_155",
    match = {
        tag = "projects",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_156",
    match = {
        tag = "im",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_157",
    match = {
        tag = "multimedia",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_158",
    match = {
        tag = "file-manager",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_159",
    match = {
        tag = terminal,
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_160",
    match = {
        tag = "settings",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_161",
    match = {
        tag = "viewer",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_162",
    match = {
        tag = "wallpaper",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_163",
    match = {
        class = "^(gedit|org.gnome.TextEditor|mousepad)$",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_164",
    match = {
        class = "^(deluge)$",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_165",
    match = {
        class = "^(seahorse)$",
    },
    opacity = "1 1",
})

hl.window_rule({
    name  = "opacity_1_1_166",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    opacity = "1 1",
})

-- SIZE

hl.window_rule({
    name  = "size__monitor_w_0_65_169",
    match = {
        tag = "KooL_Cheat",
    },
    size = { "(monitor_w*0.65)", "(monitor_h*0.9)" },
})

hl.window_rule({
    name  = "size__monitor_w_0_7__170",
    match = {
        tag = "wallpaper",
    },
    size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
})

hl.window_rule({
    name  = "size__monitor_w_0_7__171",
    match = {
        tag = "settings",
    },
    size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
})

hl.window_rule({
    name  = "size__monitor_w_0_6__172",
    match = {
        class = "^([Ff]erdium)$",
    },
    size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
})

-- BLUR & FULLSCREEN

hl.window_rule({
    name  = "no_blur_on_176",
    match = {
        tag = "games",
    },
    no_blur = true,
    fullscreen = 0,
})

hl.window_rule({
    name  = "fullscreen_0_177",
    match = {
        tag = "games",
    },
    fullscreen = 0,
})

-- This not gonna take the focus to the window that appears when 

-- hovering over some of the parts of the IntelliJ Products

hl.window_rule({
    name  = "no_initial_focus_on_181",
    match = {
        class = "^(jetbrains-*)",
    },
    -- no_initial_focus has no Lua equivalent; intentionally omitted
})

hl.window_rule({
    name  = "no_initial_focus_on_182",
    match = {
        title = "^(wind.*)$",
    },
    -- no_initial_focus has no Lua equivalent; intentionally omitted
})

-- LAYER RULES
hl.layer_rule({ match = { namespace = "rofi" }, blur = true })
hl.layer_rule({ match = { namespace = "notifications" }, blur = true })
hl.layer_rule({ match = { namespace = "quickshell:overview" }, blur = true })
hl.layer_rule({ match = { namespace = "quickshell:overview" }, ignore_alpha = 0.5 })

-- Named rules for special cases 

hl.window_rule({
    name  = "Whatsapp-zapzap",
    match = {
        class = "^([Ww]hatsapp-for-linux|ZapZap|com.rtosta.zapzap)$",
    },
    size = { "(monitor_w*0.6)", "(monitor_h*0.7)" },
    center = true,
})

hl.window_rule({
    name  = "Picture-in-Picture",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
    move = { "72%", "7%" },
    opacity = "0.95 0.75",
    pin = true,
    keep_aspect_ratio = true,
    size = { "(monitor_w*0.3)", "(monitor_h*0.3)" },
})

-- Thunar copy progress dialog

hl.window_rule({
    name  = "Thunar-Progress-bar",
    match = {
        class = "^(thunar)$",
        title = "^(File Operation Progress)$",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.26)", "(monitor_h*0.18)" },
})
