-- Generated by Wallust. Kept as a safe first-boot palette.
return {
  background = "rgb(00010B)", foreground = "rgb(E3F7F5)",
  color0 = "rgb(00010B)", color1 = "rgb(042E45)", color2 = "rgb(043249)", color3 = "rgb(033A67)",
  color4 = "rgb(065A7C)", color5 = "rgb(066489)", color6 = "rgb(83AEAA)", color7 = "rgb(CFEBE9)",
  color8 = "rgb(91A5A3)", color9 = "rgb(053E5C)", color10 = "rgb(054262)", color11 = "rgb(044E89)",
  color12 = "rgb(0778A6)", color13 = "rgb(0886B7)", color14 = "rgb(AFE8E3)", color15 = "rgb(CFEBE9)",
}
