# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(020000)
$foreground = rgb(F6E5D1)
$color0 = rgb(100E0D)
$color1 = rgb(403B38)
$color2 = rgb(6D5743)
$color3 = rgb(705D48)
$color4 = rgb(A6845A)
$color5 = rgb(AC885C)
$color6 = rgb(AC885C)
$color7 = rgb(EAD2B5)
$color8 = rgb(A4937E)
$color9 = rgb(564F4A)
$color10 = rgb(917459)
$color11 = rgb(957C5F)
$color12 = rgb(DDB078)
$color13 = rgb(E6B67B)
$color14 = rgb(E6B67B)
$color15 = rgb(EAD2B5)
