-- Hyprland 0.55+ entrypoint. Legacy .conf files are retained only as rollback.
require("UserConfigs.01-UserDefaults")
require("configs.ENVariables")
require("UserConfigs.ENVariables")
require("configs.SystemSettings")
require("UserConfigs.UserDecorations")
require("UserConfigs.UserAnimations")
require("configs.Laptops")
require("UserConfigs.Laptops")
require("UserConfigs.LaptopDisplay")
require("configs.WindowRules")
require("UserConfigs.WindowRules")
require("configs.Keybinds")
require("UserConfigs.UserKeybinds")
require("configs.Startup_Apps")
require("UserConfigs.Startup_Apps")
require("UserConfigs.UserSettings")
require("monitors")
require("workspaces")

hl.on("hyprland.start", function()
  hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/initial-boot.sh")
end)
