-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- This is a file where you put your own default apps, default search Engine etc

-- Set your default editor here uncomment and reboot to take effect.

-- NOTE, this will be automatically uncommented if you select neovim or vim to your default editor

hl.env("EDITOR", "code")
hl.env("HYPR_DOTS_TERM", "kitty")
hl.env("HYPR_DOTS_FILES", "thunar")
hl.env("HYPR_DOTS_SEARCH_ENGINE", "https://www.google.com/search?q={}")

--default editor

-- Define preferred text editor for the KooL Quick Settings Menu (SUPER SHIFT E)

-- script will take the default EDITOR and nano as fallback

local edit = "${EDITOR:-nano}"

-- These two are for UserKeybinds.conf & Waybar Modules

local term = "alacritty"

-- Terminal

local files = "thunar"

-- File Manager

-- Default Search Engine for ROFI Search (SUPER S)

local Search_Engine = "https://www.google.com/search?q={}"
