-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- NOTE, THIS FILE IS BEING USED by disabling Laptop display monitor behaviour when closing lid.

-- See notes on Laptops.conf

--monitor = eDP-1, preferred, auto, 1
