-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local colors = require("wallust.colors")

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- Decoration Settings

-- Hyprland Wiki Links

-- Animation - https://wiki.hyprland.org/Configuring/Animations/

-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Sourcing colors generated by wallust


hl.config({
    general = {
        border_size = 0,
        gaps_in = 1,
        gaps_out = 0,
        col = {
            active_border = colors.color12,
            inactive_border = colors.color10,
        },
    },
})

hl.config({
    decoration = {
        rounding = 0,
        active_opacity = 1.0,
        inactive_opacity = 0.99,
        fullscreen_opacity = 1.0,
        dim_inactive = true,
        dim_strength = 0.1,
        dim_special = 0.8,
        shadow = {
            enabled = false,
            range = 3,
            render_power = 1,
            color = colors.color12,
            color_inactive = colors.color10,
        },
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            new_optimizations = true,
            xray = true,
            ignore_opacity = true,
            special = true,
            popups = true,
        },
    },
})

hl.config({
    group = {
        groupbar = { col = { active = colors.color0 } },
        col = {
            border_active = colors.color15,
        },
    },
})
