-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict

-- if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables

-- See also Laptops.conf for laptops keybinds 

-- /* ---- ✴️ Variables ✴️ ---- */  #

local mainMod = "SUPER"

local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"

local UserScripts = os.getenv("HOME") .. "/.config/hypr/UserScripts"

local UserConfigs = os.getenv("HOME") .. "/.config/hypr/UserConfigs"

--  IMPORTANT: If you want to remap and existing keybind you MUST unbindd it first 

-- The bindings are CASE SENSITIVE. We suggest you copy the exisitng binding here

--  Then change `bindd` to `unbind`

-- E.g. 

-- unbind = $mainMod, Return, Open terminal, exec, $term

-- bindd = $mainMod, Return, Open terminal, exec, ghostty 

--

-- unbind = $mainMod, E, file manager, exec, $files

-- bindd = $mainMod, T, file manager, exec, $files

-- If you are ADDING a bindd, make sure you include the description 

-- Other the keybind search menu might not show it properly 

-- E.g.

-- bindd = $mainMod, Z, My z app, exec APPNAME

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("code"))

-- For passthrough keyboard into a VM

-- bind = $mainMod ALT, P, submap, passthru

--submap = passthru

-- to unbind

--bind = $mainMod ALT, P, submap, reset

--submap = reset
