-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- User Settings

-- This is where you put your own settings as this will not be touched during update 

-- if the upgrade.sh is used.

-- refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/

-- NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf

--

-- Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this


hl.config({
    input = {
        touchpad = {
            -- The PIXA3848 touchpad can get stuck in libinput palm suppression after boot.
            disable_while_typing = false,
        },
    },
})

hl.config({
    cursor = {
        -- On this Hyprland 0.55 + PIXA3848 setup, no_warps can leave the visible
        -- pointer stuck even while libinput is receiving touchpad motion.
        no_warps = false,
    },
})


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("socat -u UNIX-CONNECT:" .. os.getenv("XDG_RUNTIME_DIR") .. "/hypr/" .. os.getenv("HYPRLAND_INSTANCE_SIGNATURE") .. "/.socket2.sock - | while read -r _; do pkill -RTMIN+8 waybar; done")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/FixPointer.sh")
end)
