-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

-- For window rules and layerrules

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- This file is used to add or overwrite window rules 

-- This file will not be modified during dotfiles updates
