# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6E5D1
background         #020000
cursor             #C4AD95

active_tab_foreground     #020000
active_tab_background     #F6E5D1
inactive_tab_foreground   #F6E5D1
inactive_tab_background   #020000

active_border_color   #F6E5D1
inactive_border_color #020000
bell_border_color     #403B38

color0      #100E0D
color1		#403B38
color2		#6D5743
color3		#705D48
color4		#A6845A
color5		#AC885C
color6		#AC885C
color7		#EAD2B5
color8		#A4937E
color9		#564F4A
color10		#917459
color11		#957C5F
color12		#DDB078
color13		#E6B67B
color14		#E6B67B
color15		#EAD2B5
